### ISSUE TITLE
slash in node (file/folder) name

### ISSUE THREAD

**Issue by patatetom** [adoxa/regdump#1]
hi,
sometimes, the slash character is in the name of the node :
`/ControlSet001/Enum/USBSTOR/CdRom&Ven_Dell&Prod_DVD+/-RW_DW316&Rev_A1C0`
which disturbs searches using tools such as `grep`, `cut` or even `awk` : would it be possible to replace it with this one which is very close visually : 
` ⁄  ` (U+2044)
regards.

**Comment by adoxa** [comment]
I suppose I could do that in non-Windows, where it would be reasonable to assume UTF-8, but not so much in Windows, where I cannot. Another approach is to make it `<2F>` (or use backslash for the separator (it's invalid in keys) and `<5C>` in values, but I suspect you wouldn't really like that).

**Comment by patatetom** [comment]
hi,
I'm under Linux (so with UTF-8) and your code compiles with `gcc` without any problem : where would happen the modification to modify the display (replace `/` by something else in the node name) ?
if this modification is too complicated, then the "Windows style" would finally be the most appropriate, i.e. `\` for the path separator.
regards.

**Comment by adoxa** [comment]
Modify each of the ifs in `make_name`.

```c
if (*uc == '/')
    out += sprintf( out, "\xe2\x81\x84" );
else if (*uc >= 32 ...
// and same with *us
```

That will translate `/` to the UTF-8 fraction slash.

**Comment by patatetom** [comment]
great 👍, it's working perfectly !

```diff
diff --git a/regdump.c b/regdump.c
index b23752e..b75e08a 100644
--- a/regdump.c
+++ b/regdump.c
@@ -173,7 +173,9 @@ char* make_name( char* out, char* in, int len, int comp )
     unsigned char* uc = (unsigned char*)in;
     for (i = 0; i < len; ++uc, ++i)
     {
-      if (*uc >= 32 && *uc < 127)
+      if (*uc == '/')
+	out += sprintf( out, "\xe2\x81\x84" );
+      else if (*uc >= 32 && *uc < 127)
 	*out++ = *uc;
       else
 	out += sprintf( out, "<%02X>", *uc );
@@ -184,7 +186,9 @@ char* make_name( char* out, char* in, int len, int comp )
     unsigned short* us = (unsigned short*)in;
     for (i = 0; i < len / 2; ++us, ++i)
     {
-      if (*us >= 32 && *us < 127)
+      if (*us == '/')
+	out += sprintf( out, "\xe2\x81\x84" );
+      else if (*us >= 32 && *us < 127)
 	*out++ = (char)*us;
       else
 	out += sprintf( out, "<%0*X>", (*us < 0x100) ? 2 : 4, *us );
```

but in fact, there are quite a few nodes that contain the `/` character :
```
CdRom&Ven_Dell&Prod_DVD+⁄-RW_DW316&Rev_A1C0
Intel 82443LX⁄EX
I⁄O
SCSI#DiskMATSHITALS-120⁄240____00
Size⁄Small⁄Medium⁄Large
Standard TCP⁄IP
TCP⁄IP
http:⁄⁄*:2869⁄
http:⁄⁄*:5357⁄
http:⁄⁄+:10243⁄WMPNSSv4⁄
http:⁄⁄+:47001⁄wsman⁄
http:⁄⁄+:5985⁄wsman⁄
http:⁄⁄+:80⁄116B57EB-ECE2-41ac-8429-9F9E963361B7⁄
http:⁄⁄+:80⁄Temporary_Listen_Addresses⁄
http:⁄⁄www.microsoft.com⁄provisioning⁄eaptlsconnectionpropertiesv1
http:⁄⁄www.microsoft.com⁄provisioning⁄eaptlsuserpropertiesv1
http:⁄⁄www.microsoft.com⁄provisioning⁄mschapv2connectionpropertiesv1
http:⁄⁄www.microsoft.com⁄provisioning⁄mschapv2userpropertiesv1
http:⁄⁄www.microsoft.com⁄provisioning⁄mspeapconnectionpropertiesv1
http:⁄⁄www.microsoft.com⁄provisioning⁄mspeapuserpropertiesv1
https:⁄⁄*:5358⁄
https:⁄⁄+:10245⁄WMPNSSv4⁄
https:⁄⁄+:443⁄C574AC31-5794-4AEE-B1BB-6651C5315029⁄
https:⁄⁄+:443⁄sra_{BA19C980-CD49-458b-9E23-C84EE0ADCD75}⁄
https:⁄⁄+:5986⁄wsman⁄
```
and it's not sure that this modification is a good change for the one who would like to search for an URL... the "windows style" (`\` as path separator) may finally be preferable.
thanks a lot.
regards

**Comment by adoxa** [comment]
You can change the separator by searching for `'/'` and replacing with `'\\'` (there's two). But that just shifts the problem, as values may contain it, so you could have something like `...\key\C:\path\value`.

**Comment by patatetom** [comment]
that's right, thank you for the remark.
the important thing for me was that the character `/` of the node name "broke" the path.
thanks for `regdump` and the help **adoxa**.
regards.
